name: Shell commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
    steps:
      - name: echo a string
        run: echoOO " Test  Action_runner_debug"  # Throw error we can see it  in Debug mode config!
      - name: multiline script
        run: |
          python3 -V
          touch my_file_with_workflow.py
          ls -l
